[versions]
# Plugin versions
agp = "8.9.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
parcelize = "2.0.0"

# AndroidX versions
appcompat = "1.7.0"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
coreSplashscreen = "1.0.1"
preferenceKtx = "1.2.1"
workRuntime = "2.10.1"
lifecycle = "2.8.2"
navigation = "2.8.9"
room = "2.7.1"

# Google Play Services
playServicesBase = "18.7.0"
googlePlayServicesMlkitSubjectSegmentationVersion = "16.0.0-beta1"

# UI Libraries
material = "1.12.0"
blurview = "2.0.6"
circleindicator = "2.1.6"
collapsingtoolbarlayoutSubtitle = "1.5.0"
colorpickerVersion = "1.1.0"
dotsindicator = "5.1.0"
fadingedgelayout = "1.0.0"
flexbox = "3.0.0"
viewpager2 = "1.1.0"
recyclerview = "1.4.0"
recyclerviewSelection = "1.1.0"

# Networking
okhttp = "4.12.0"
glide = "4.16.0"

# Dependency Injection
hilt = "2.51.1"

# Coroutines
kotlinxCoroutinesAndroid = "1.10.2"

# Database
room = "2.7.1"

# Utility
commonsText = "1.13.1"
gson = "2.10.1"
guava = "33.4.8-jre"
jsoup = "1.20.1"
slf4jApi = "2.0.17"
zip4j = "2.11.5"

# Xposed
xposedbridge = "main-SNAPSHOT"

# Root
libsuVersion = "6.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version = "1.2.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version = "2.8.9" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.8.9" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version = "1.0.0" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version = "1.80" }
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
collapsingtoolbarlayout-subtitle = { module = "com.hendraanggrian.material:collapsingtoolbarlayout-subtitle", version.ref = "collapsingtoolbarlayoutSubtitle" }
com-google-android-gms-play-services-mlkit-subject-segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "googlePlayServicesMlkitSubjectSegmentationVersion" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
eventbus = { module = "org.greenrobot:eventbus", version = "3.3.1" }
fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version.ref = "fadingedgelayout" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jaredrummler-colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpickerVersion" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
library = { module = "com.android.databinding:library", version = "8.9.2" }
lottie = { module = "com.airbnb.android:lottie", version = "6.6.6" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version = "0.8" }
room-compiler = { module = "androidx.room:room-compiler", version = "2.7.1" }
room-ktx = { module = "androidx.room:room-ktx", version = "2.7.1" }
room-runtime = { module = "androidx.room:room-runtime", version = "2.7.1" }
su-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsuVersion" }
su-nio = { module = "com.github.topjohnwu.libsu:nio", version.ref = "libsuVersion" }
su-service = { module = "com.github.topjohnwu.libsu:service", version.ref = "libsuVersion" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
xposedbridge = { module = "com.github.Mahmud0808:XposedBridge", version.ref = "xposedbridge" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

[plugins]
# Android Gradle Plugin
agp-app = { id = "com.android.application", version.ref = "agp" }

# Kotlin Plugins
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }

# Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }